name: Deploy to AWS with Terraform

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  deploy-iac:
    runs-on: [self-hosted, terraform]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:

      # ------------------------------
      # Checkout Repo
      # ------------------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # ------------------------------
      # Setup Terraform
      # ------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # ------------------------------
      # Install tfsec
      # ------------------------------
      - name: Install tfsec
        run: |
          curl -sLo tfsec https://github.com/aquasecurity/tfsec/releases/download/v1.28.11/tfsec-linux-amd64
          chmod +x tfsec

      # ------------------------------
      # Terraform Init
      # ------------------------------
      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt || true

      - name: Terraform Validate
        run: terraform validate

      - name: TFSEC Security Scan
        run: ./tfsec . || true

      - name: Terraform Plan
        run: terraform plan

      # ------------------------------------------------------
      # ‚≠ê Import existing nginx ingress into Terraform (safe)
      # ------------------------------------------------------


      # ------------------------------
      # Terraform Apply
      # ------------------------------
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # ------------------------------
      # Install kubectl
      # ------------------------------
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # ------------------------------
      # Install Helm
      # -------------------------
